{{/* babylon-runner/helm/templates/hpa.yaml */}}
{{- if and .Values.deploy .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "babylon-runner.fullname" . }}
  namespace: {{ include "babylon-runner.namespaceName" . }}
  labels:
    {{- include "babylon-runner.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "babylon-runner.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleUp.maxPods }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleDown.maxPods }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds }}
{{- end }}
