{{/* babylon-runner/helm/templates/service.yaml */}}
{{- if .Values.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "babylon-runner.fullname" . }}-metrics
  namespace: {{ include "babylon-runner.namespaceName" . }}
  labels:
    {{- include "babylon-runner.labels" . | nindent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.config.metricsPort | default 9093 }}
    targetPort: metrics
  selector:
    {{- include "babylon-runner.selectorLabels" . | nindent 4 }}
{{- end }}
